# Generated by Django 4.0.5 on 2022-09-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='contato',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ramo',
            field=models.CharField(max_length=14),
        ),
    ]
