# Generated by Django 4.0.5 on 2022-09-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_nome_alter_usuario_cpf_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
